### ISSUE TITLE
请问大神，点测试openai api出现502报错是什么原因

### ISSUE THREAD

**Issue by tianxiazaiwo** [MaoXiaoYuZ/Long-Novel-GPT#11]
详细报错信息：
User:Say this is a test
(ERROR)gpt-4-1106-preview:Error code: 502
(ERROR)gpt-3.5-turbo-1106:Error code: 502

截图如下：
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/51230b7b-7f86-48fa-8fb2-0cbdfdf42771)

基本情况说明：申请成功了openai api秘钥，暂时没绑信用卡

**Comment by MaoXiaoYuZ** [comment]
把base_url删了试试

**Comment by tianxiazaiwo** [comment]
好的，谢谢，我试试。
每次运行都需要启动下服务吗？（如下红框中的命令）即先运行服务，再在浏览器输入诸如127.0.0.1的地址对吧
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/4c66246a-b573-4949-8d39-fef8504ad237)


> 把base_url删掉试试

**Comment by tianxiazaiwo** [comment]
> 把base_url删掉试试

去掉后，报这个错：
User:Say this is a test
(ERROR)gpt-4-1106-preview:Connection error.
(ERROR)gpt-3.5-turbo-1106:Connection error.

截图如下：
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/3c6c57dc-66d3-49de-b703-38e1c65a0659)

**Comment by MaoXiaoYuZ** [comment]
先说下你一开始填的那个base_url是用于ChatGPT的，所以需要删掉，你目前无法连接openai.com，大概率是网络问题。

**Comment by MaoXiaoYuZ** [comment]
ChatGPT和openai api是两个东西，选其一即可

**Comment by tianxiazaiwo** [comment]
> 先说下你开始填的那个base_url是用于ChatGPT的，所以需要删掉，你目前无法连接openai.com，很大概率是网络问题。

程序新手求问：有可能是安装的问题吗，不知道是不是我某些包没安装好。
我是用vpn的，就浏览器访问来看，可以正常访问openai官网的、登录和用chatgpt也没问题

**Comment by MaoXiaoYuZ** [comment]
那你运行下面的python程序测试下，这是openai-python官方的例子：
```
from openai import OpenAI

client = OpenAI(
    api_key="sk-............................",  //这里填你的api_key
)

stream = client.chat.completions.create(
    model="gpt-3.5-turbo",
    messages=[{"role": "user", "content": "Say this is a test"}],
    stream=True,
)
for chunk in stream:
    print(chunk.choices[0].delta.content or "", end="")
```

**Comment by tianxiazaiwo** [comment]
> 那你运行下面的python程序测试下，这是openai-python官方的例子：
> 
> ```
> from openai import OpenAI
> 
> client = OpenAI(
>     api_key="sk-............................",  #这里填你的api_key
> )
> 
> stream = client.chat.completions.create(
>     model="gpt-3.5-turbo",
>     messages=[{"role": "user", "content": "Say this is a test"}],
>     stream=True,
> )
> for chunk in stream:
>     print(chunk.choices[0].delta.content or "", end="")
> ```

您好，我将您这个文件保存成OpenAITest.py文件后，按如下命令运行，得到了如下提示，请问这个提示的意思是那个部分没安装好的意思吗？
(base) PS C:\Users\Administrator> conda activate lngpt
(lngpt) PS C:\Users\Administrator> cd d:\ai\
(lngpt) PS D:\ai> python OpenAITest.py
Traceback (most recent call last):
  File "D:\ai\OpenAITest.py", line 7, in <module>
    stream = client.chat.completions.create(
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\resources\chat\completions.py", line 663, in create
    return self._post(
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_base_client.py", line 889, in request
    return self._request(
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_base_client.py", line 965, in _request
    return self._retry_request(
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_base_client.py", line 1013, in _retry_request
    return self._request(
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_base_client.py", line 965, in _request
    return self._retry_request(
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_base_client.py", line 1013, in _retry_request
    return self._request(
  File "C:\ProgramData\miniconda3\envs\lngpt\lib\site-packages\openai\_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}
(lngpt) PS D:\ai>

**Comment by tianxiazaiwo** [comment]
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/83ac2de1-8ee4-433b-b326-9d2472338f20)

**Comment by MaoXiaoYuZ** [comment]
这说明钱不够了

**Comment by tianxiazaiwo** [comment]
> 这说明钱不够了

openai必须要绑定信用卡吗？那之后运行程序是否都会按token付费，不管是用chatgpt3.5还是4？
调用openai api是否跟chatgpt3.5还是4有关？前期测试，我想用3.5，免费的，程序是否可以设置？
对openai方面是新手，麻烦空了帮忙解答下，非常感谢

**Comment by MaoXiaoYuZ** [comment]
关于openai本身的一些内容不在本项目讨论范围内。至于是否可以用3.5，用3.5的话效果会差很多，当然用于尝试下也没问题。

**Comment by tianxiazaiwo** [comment]
> 关于openai本身的一些内容不在本项目讨论范围内。至于是否可以用3.5，用3.5的话效果会差很多，当然用于尝试下也没问题。

程序中没有设置3.5还是4.0的地方对吧，默认是4，所以需要将自己的openai 绑定信用卡才能使用？
