### ISSUE TITLE
请问下，文心一言配置出现这种报错怎么解决？

### ISSUE THREAD

**Issue by tianxiazaiwo** [MaoXiaoYuZ/Long-Novel-GPT#13]
你好，大佬，出现这种错误怎么解决，
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/c0a362be-4f6c-4fb3-b993-58c4faf7d21f)

我网上查了解决方案，还是没没找到。
百度智能云中也也建了一个应用，如下图
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/78161c2a-2403-4326-9556-7fb09f98eeba)
配置页面中应该不是填建的这个应用的api key和Secret Key，因为早前我填这个也试了，报api return error, req_id:  code: 14, msg: IAM Certification failed的错，当时我根据百度官方的文档，重新申请了这个安全认证，目前文心一言配置页面填的是下方截图中的这两个，
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/c952389b-db23-4629-98e7-3c24d9244638)

**Comment by MaoXiaoYuZ** [comment]
你好，你可以先试试官方提供的api调用例子（python），看看是否有问题。

**Comment by tianxiazaiwo** [comment]
> 你好，你可以先试试官方提供的api调用例子（python），看看是否有问题。

您好，好像没问题，运行调用例子，里面没有出现error相关的提示，麻烦您空了帮忙看下
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/21039255/28d325ec-8098-4929-9bf9-e4090bf6e16f)

{"refresh_token":"25.e048ed7d0f48daeecf4c3d5c3f43c5ba.315360000.2026137409.282335-57116249","expires_in":2592000,"session_key":"9mzdA8\/ET9badkQVqEIFAci6I\/I7U677Rhb4NzaKCRSpp3X9e7VSPwbhmlS7j8aq1AtoJtF+VG+EXCeOFV6jMLk+AauNeg==","access_token":"24.8e4d44e61d77ecf559b05ad14eedcfa9.2592000.1713369409.282335-57116249","scope":"public ai_custom_qianfan_bloomz_7b_compressed ai_custom_yiyan_com ai_custom_yiyan_com_8k ai_custom_yiyan_com_ai_apaas ai_custom_yiyan_com_aquilachat_7b ai_custom_yiyan_com_bloomz7b1 ai_custom_yiyan_com_chatglm2_6b_32k ai_custom_yiyan_com_chatlaw ai_custom_yiyan_com_codellama_7b_ins ai_custom_yiyan_com_eb_instant ai_custom_yiyan_com_eb_pro ai_custom_yiyan_com_eb_turbo_pro ai_custom_yiyan_com_eb_turbo_pro_128k ai_custom_yiyan_com_emb_bge_large_en ai_custom_yiyan_com_emb_bge_large_zh ai_custom_yiyan_com_emb_tao_8k ai_custom_yiyan_com_emb_text ai_custom_yiyan_com_ernie_35_4k_0205 ai_custom_yiyan_com_ernie_35_8k_0205 ai_custom_yiyan_com_ernie_35_8k_1222 ai_custom_yiyan_com_ernie_lite_8k ai_custom_yiyan_com_gemma_7b_it ai_custom_yiyan_com_llama2_13b ai_custom_yiyan_com_llama2_70b ai_custom_yiyan_com_llama2_7b ai_custom_yiyan_com_mixtral_8x7b ai_custom_yiyan_com_qf_chinese_llama_2_13b ai_custom_yiyan_com_qianfan_chinese_llama_2_7b ai_custom_yiyan_com_sd_xl ai_custom_yiyan_com_sqlcoder_7b ai_custom_yiyan_com_tokenizer_eb ai_custom_yiyan_com_xuanyuan_70b_chat ai_custom_yiyan_com_yi_34b brain_all_scope wenxinworkshop_mgr wise_adapt lebo_resource_base lightservice_public hetu_basic lightcms_map_poi kaidian_kaidian ApsMisTest_Test\u6743\u9650 vis-classify_flower lpq_\u5f00\u653e cop_helloScope ApsMis_fangdi_permission smartapp_snsapi_base smartapp_mapp_dev_manage iop_autocar oauth_tp_app smartapp_smart_game_openapi oauth_sessionkey smartapp_swanid_verify smartapp_opensource_openapi smartapp_opensource_recapi fake_face_detect_\u5f00\u653eScope vis-ocr_\u865a\u62df\u4eba\u7269\u52a9\u7406 idl-video_\u865a\u62df\u4eba\u7269\u52a9\u7406 smartapp_component smartapp_search_plugin avatar_video_test b2b_tp_openapi b2b_tp_openapi_online smartapp_gov_aladin_to_xcx","session_secret":"cf0fd44c41db7d97c0c48ccda0adb300"}

**Comment by tianxiazaiwo** [comment]
重启多次，可以测试成功了。现在有遇到这种问题，生成到一半的时候出现这种报错，多次出现
关掉科学shangp上网工具和不关都测试了，都会出现这种问题，可能是什么原因？

**Comment by MaoXiaoYuZ** [comment]
这是文心一言的适配问题，后续我会推送更新来解决。

**Comment by tianxiazaiwo** [comment]
> 这是文心一言的适配问题，后续我会推送更新来解决。

好的，感谢，希望能尽快推送更新

**Comment by MaoXiaoYuZ** [comment]
已适配；在这个网址获取ak和sk:
[qianfan](https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application)

**Comment by tianxiazaiwo** [comment]
> 已适配；在这个网址获取ak和sk: [qianfan](https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application)

非常感谢。我试试

**Comment by tianxiazaiwo** [comment]
> 已适配；在这个网址获取ak和sk: [qianfan](https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application)

重新下载github文件后，在本地miniconda3 shell按步骤运行，运行到 python  demo/app.py报错：ModuleNotFoundError: No module named 'promptflow'。之前运行这句都是出现包含http://127.0.0.1:7860/的提示语句
具体如下：
(lngpt) PS D:\ai\Long-Novel-GPT-main> python demo/app.py
>>
Traceback (most recent call last):
  File "D:\ai\Long-Novel-GPT-main\demo\app.py", line 11, in <module>
    from demo.tab_main_page import tab_main_page
  File "D:\ai\Long-Novel-GPT-main\demo\tab_main_page.py", line 4, in <module>
    from demo.wrapper_for_demo import Long_Novel_GPT_Wrapper
  File "D:\ai\Long-Novel-GPT-main\demo\wrapper_for_demo.py", line 4, in <module>
    from demo.pipeline import Long_Novel_GPT_DEMO
  File "D:\ai\Long-Novel-GPT-main\demo\pipeline.py", line 4, in <module>
    from layers.chapters_writer import ChaptersWriter
  File "D:\ai\Long-Novel-GPT-main\layers\chapters_writer.py", line 6, in <module>
    from prompts.load_utils import run_prompt
  File "D:\ai\Long-Novel-GPT-main\prompts\load_utils.py", line 1, in <module>
    from promptflow import load_flow
ModuleNotFoundError: No module named 'promptflow'

**Comment by MaoXiaoYuZ** [comment]
抱歉没有及时回复，刚刚推送了一个新版本，可以看看。

对于这个问题，说明缺少了promptflow包，执行 pip install promptflow 即可。
