### ISSUE TITLE
[feature request] 支持 Ollama 等本地 LLM

### ISSUE THREAD

**Issue by Mingzefei** [MaoXiaoYuZ/Long-Novel-GPT#14]
本地部署了一个针对小说微调的 LLM，并接入 Ollama，初步测试效果还可以。
打算借助该项目进一步提高效率。

**Comment by MaoXiaoYuZ** [comment]
目前无相关计划。

**Comment by Mingzefei** [comment]
经测试，该问题可以通过 Ollama 端操作解决：
1. Ollama 端：`ollama cp your_llm_name gpt-3.5-turbo-1106`
2. Long-Novel-GPT 设置页面：openai api_key 填写 `ollama`，openai base_url 填写 Ollama server 地址。

**Comment by aiaimimi0920** [comment]
小说微调的llm 生成的小说可读性如何？能签约吗？@Mingzefei

**Comment by Mingzefei** [comment]
> 小说微调的llm 生成的小说可读性如何？能签约吗？@Mingzefei

最终效果受多方面影响。我主要用于生成特定题材、语言风格的中文小说，效果比ChatGPT更稳定、可读性更好，暂没有测试签约。
@aiaimimi0920
