### ISSUE TITLE
生成章节后如何进一步生成正文？

### ISSUE THREAD

**Issue by Mingzefei** [MaoXiaoYuZ/Long-Novel-GPT#15]
已做的尝试：
（均已正常生成章节）
1. 在`生成章节`页面勾选`全部章节`，`生成正文`页面的`章节剧情`栏中仅有 小说名、这是一部什么样的小说、大纲，**没有具体的章节**。
2. 在`生成章节`页面勾选`第1章节`，`生成正文`页面的`章节剧情`栏中出现了生成的第1章节及其他小说信息，进行`新建正文`等操作后，返回`生成章节`页面勾选`第2章节`，`生成正文`页面的`章节剧情`栏中**仍显示生成的第1章节**。
3. 多次进行`生成正文`操作后，仅显示`（已省略）`。

**Comment by MaoXiaoYuZ** [comment]
推送了一个新版本，可以试试
