### ISSUE TITLE
运行demo文件时编码报错

### ISSUE THREAD

**Issue by zhuxingyue-2000** [MaoXiaoYuZ/Long-Novel-GPT#16]
在运行app.py时，报错UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2009: illegal multibyte sequence。
修改component_meta.py 文件中为“source_code = source_file.read_text(encoding='utf-8')”或“source_code = source_file.read_text(errors='ignore')”均无法解决

**Comment by MaoXiaoYuZ** [comment]
将promptflow版本设为1.6.0
