### ISSUE TITLE
大佬，属于半小白类型，可否能够写上安装教程，我用Anaconda Prompt 命令安装了前两个并激活，但是pip install -r requirements.txt始终出现错误。是需要把代码全部下载下来吗？下载下来了之后放在哪里可以被检测呢？

### ISSUE THREAD

**Issue by yangchangda2022** [MaoXiaoYuZ/Long-Novel-GPT#18]
大佬，属于半小白类型，可否能够写上安装教程，我用Anaconda Prompt 命令安装了前两个并激活，但是pip install -r requirements.txt始终出现错误。是需要把代码全部下载下来吗？下载下来了之后放在哪里可以被检测呢？

**Comment by MaoXiaoYuZ** [comment]
确实目前安装流程对小白来说不友好，可以先关注这个项目，之后会提供更便捷的方式，例如docker之类的。
