### ISSUE TITLE
Error "Execution failure in 'parser': (IndexError) list index out of range"

### ISSUE THREAD

**Issue by qinqinhan** [MaoXiaoYuZ/Long-Novel-GPT#20]
文心3.5 生成章节的时候提示超出范围
![1](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/112688130/9aef3470-0b8d-4243-92ba-12955c9145b9)

**Comment by MaoXiaoYuZ** [comment]
抱歉没有及时回复，刚刚推送了一个新版本，可以看看。
