### ISSUE TITLE
关于 Long-Novel-GPT 1.4 使用第三方 API 遇到问题

### ISSUE THREAD

**Issue by ez21502** [MaoXiaoYuZ/Long-Novel-GPT#21]
我尝试使用 Long-Novel-GPT 1.4 连接第三方OpenAI协议标准的API (网关由原来的 https://api.openai.com 替换为 https://api.openai-hk.com
备用网关: https://twapi.openai-hk.com，和https://www.gpt4novel.com/api/xiaoshuoai/v1/)，但遇到了以下问题：
1 模型找不到： 初始配置中使用了默认模型名称，但 API 返回 "Model not found" 错误。
2列表索引错误： 将模型名称改为 gpt-3.5-turbo 和 gpt-4 后，出现 "list indices must be integers or slices, not NoneType" 错误。
3连接错误：(ERROR)gpt-4-1106-preview:Connection error.
(ERROR)gpt-3.5-turbo-1106:Connection error.
尝试的解决方案：

确认模型名称
确认 API 配置
检查代码中的列表操作
使用绝对导入
将脚本作为模块运行
修改 sys.path
调用 set_gpt_api_config 函数
使用新版 OpenAI API 接口

都没用

**Comment by wandanan** [comment]
可以替换的，是你设置没整对
