### ISSUE TITLE
可以使用本地模型吗？

### ISSUE THREAD

**Issue by Johnnydaszhu** [MaoXiaoYuZ/Long-Novel-GPT#22]
比如lm studio接入这样

**Comment by MaoXiaoYuZ** [comment]
主要是本地模型太弱了，即使能生成小说也完全没法看。

**Comment by Johnnydaszhu** [comment]
> 主要是本地模型太弱了，即使能生成小说也完全没法看。

新的模型还可以啊，主要是是错成本下来了，然后以后能力强了就很可用了

**Comment by Mingzefei** [comment]
可以参考 https://github.com/MaoXiaoYuZ/Long-Novel-GPT/issues/14#issuecomment-2005998742 这个。
@Johnnydaszhu
