### ISSUE TITLE
“未能定位到submit按钮”

### ISSUE THREAD

**Issue by user061501** [MaoXiaoYuZ/Long-Novel-GPT#23]
您好！ 在版本1.5上测试http://localhost:8000/v1/时，显示错误：
in wait_submit_image
    raise Exception("未能定位到submit按钮！(Failed to locate the submit button!)")
Exception: 未能定位到submit按钮！(Failed to locate the submit button!)
请问如何进行下一步呢？

还想问下，直接使用ChatGPT时有两个显著的问题，一是它的生成字数似乎有上限不能直接写完一整篇，二是当尝试逐一章节写时它会在写第二章时忘记第一章里写了什么，需要特意提醒第一章内容，提醒后又会忘记第二章写了什么，整体上逻辑很难实现连贯。请问这个项目里这两个问题还会出现吗？

另外，这个项目支持导入文件吗？

谢谢！

**Comment by MaoXiaoYuZ** [comment]
剧情的连贯性问题相信会在后续的更新中一步步完善，敬请关注。
新版本已发布，可以尝试在线demo。
