### ISSUE TITLE
重新配置第三方模型，测试通过，但是正式生成报错。

### ISSUE THREAD

**Issue by XlenWork** [MaoXiaoYuZ/Long-Novel-GPT#24]
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/174002937/f3f4c19c-3632-4593-ba4f-fe64f00bab88)
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/174002937/33f23424-0d9b-4651-9a0a-5d574a8ef5c4)

为什么会报这种歌错呢？在设置的测试已经测试成功了！

**Comment by MaoXiaoYuZ** [comment]
因为你改动了openai的模型名称，但实际上你在app中选择模型时，传入的模型名称还是原来的（例如：gpt-3或gpt-4）。

我建议你不要修改gpt-model-config这个字典。

**Comment by XlenWork** [comment]
我看了代码不少地方都是写死的配置，能不能吧这些做成一个变量呢？这样就可以配置不同的模型进去测试生成效果？

**Comment by XlenWork** [comment]
还有一个关于交互的问题，每次都要去设置那里点一次测试API，API的key才会生效，挺尴尬的~~
