### ISSUE TITLE
剧情连续问题

### ISSUE THREAD

**Issue by wandanan** [MaoXiaoYuZ/Long-Novel-GPT#28]

**Comment by wandanan** [comment]
生成修改了一章之后，下一章的剧情，如何去上一章的结尾剧情保持连贯？

寒冬的办公室，依然是那样冰冷且充满敌意。张鹤之坐在自己的小隔间里，身心疲累不堪。今天，这已经是他第三次被上司张强狠狠地训斥。张强的声音如毒蛇般钻进他的耳朵，使他不禁颤抖。

"你干的这是什么工作？！一个策划案都做不好，还想留在公司，做梦吧你！"张强怒不可遏地指着张鹤之的鼻子，眼神里充斥着厌恶和鄙视。

张鹤之咬着牙，脸色苍白，他努力让自己看起来镇定一些，但内心的绝望却如洪水般涌来。再这样下去，他不仅会失去工作，还会失去那仅有的经济来源。想到那个900元的小单间，那碗泡面，那纸片老婆，所有的一切都将在顷刻间崩塌。

他忍不住回忆起过去。三年前，他满怀希望地从一所普通大学毕业，带着满腔热血进入社会。当时他选择了这家公司，因为它承诺有很大的发展空间和薪资待遇。起初，情况似乎还不错，他得到了几次小的升职机会，并在团队中赢得了一些尊重。然而，随着经济形势的变化，公司开始裁员，这让他感到了危机。

一个朋友曾建议他换一份工作，但是为了让家里病重的母亲能有稳定的医疗费来源，他不得不选择继续坚守在这份工作岗位上。灰暗的前景和不断增加的工作压力，让他渐渐变得麻木且疲惫。

拖着疲惫的身躯回到出租屋，张鹤之还没来得及将衣服挂到墙上，房东已经敲响了他的房门。"房租，该缴了！"房东的语气毫不留情，让他感到一丝刺骨的寒意。

"好吧，我尽快。"张鹤之无奈地答应，心中只有更多的失落。打开手机，发现短信提示余额不足，连与朋友联系的机会都被切断了。

他懊恼地扔下手机，躺在那单薄的床垫上，望着天花板，脑海里不停浮现出那该死的策划案，失业后的每个可能情景在他脑中盘旋。一瞬间，他竟产生了一种放弃一切的念头，那种无尽的绝望让他感到万念俱灰。

就在这时，脑中突然传来一个清晰的声音，仿佛从另一个世界传来。"宿主，您已获得破解现实世界规则的能力，请进行尝试。"

张鹤之猛地愣住了，不敢相信自己的耳朵。究竟是他太疲劳产生了幻觉，还是这个冰冷的现实终于向他展露了一丝温情？

"这是在做梦吗？"张鹤之自言自语，尝试捏了一下自己的手背，清晰的疼痛让他意识到这一切是真的。

在他的注视下，放在桌边的旧闹钟突然发出微弱的光芒。随着光芒越来越强，闹钟的指针开始迅速倒转，回到了两分钟前。他刚才喝洒了一地的水杯完好无损地躺在桌上，仿佛一切都未发生过。这个神奇的变化令他大惊失色。

系统的声音再次响起："您可以改变现实的属性，赋予它新的功能。但请注意，使用能力需消耗精神力，过度使用可能对身体造成伤害。"

张鹤之的目光变得坚定起来，他下意识地握紧了拳头。内心的狂喜渐渐被冷静和计划取代。这真正的力量让他感到无比振奋，但他同时也意识到，想要彻底改变命运，还需要谨慎行事和不断试验。

为了熟悉和掌握这份能力，张鹤之决定从一些简单的事情开始。他将卧室的灯泡取下来，然后集中精神试图改变其亮度属性。结果灯泡突然闪烁了一下，光线变得比之前更加明亮。这次试验的成功让他信心倍增，但随后出现的头晕目眩也提醒着他这个能力的代价。

“需要找到一个平衡点，”张鹤之默默对自己说。他还记得大学时期他非常理想主义的自己，每天读书到深夜，做着各种天马行空的计划。而今，他终于有机会实现那些梦想了，但是他必须保持警觉。

随着时间的推移，张鹤之逐渐掌握了这个系统的能力和限制。他开始尝试一些小范围的空间操控，比如暂时改变办公桌的大小，以便更有效率地工作。这在早期并未引起任何人的注意，但他显然感觉到自己的工作效率有了显著提升。

“张鹤之，你这个月的业绩居然提升了这么多？”同事李铭在月底的总结会上对他说。张鹤之混掺了个笑，心里却更加坚定了要善用系统的决心。

然而，每次试验成功带来的振奋，也伴随着偶尔的失败挫折。例如，一次他试图让纸片老婆变成真实人物，却因为过度消耗精神力而晕倒，还好并未留下后遗症。这使他更加警觉，明白必须稳扎稳打，切勿急于求成。

与此同时，公司内部的项目招标会将至，这次招标会是公司未来几年的重磅项目，决定了很多同事的前途与命运。在筹备会上，张鹤之捕捉到了一个重要的信息：一个友善的老同事告诉他，有一个尚未公布的内部消息，这次招标会的具体内容可能与他手上的一个未完成的策划案有很大联系。

“也许，这就是我的机会。”张鹤之心中萌生出新的希望。通过系统赋予的力量，他不仅要保护自己，更要抓住这一难得的机遇，去改变现有的命运轨迹。

张鹤之深深吸了一口气，准备好了迎接未知的挑战。

**Comment by wandanan** [comment]
寒冬的办公室，依然是那样冰冷且充满敌意。张鹤之坐在自己的小隔间里，身心疲累不堪。今天，这已经是他第三次被上司张强狠狠地训斥。张强的声音如毒蛇般钻进他的耳朵，使他不禁颤抖。

"你干的这是什么工作？！一个策划案都做不好，还想留在公司，做梦吧你！"张强怒不可遏地指着张鹤之的鼻子，眼神里充斥着厌恶和鄙视。

张鹤之咬着牙，脸色苍白，他努力让自己看起来镇定一些，但内心的绝望却如洪水般涌来。再这样下去，他不仅会失去工作，还会失去那仅有的经济来源。想到那个900元的小单间，那碗泡面，那纸片老婆，所有的一切都将在顷刻间崩塌。

他忍不住回忆起过去。三年前，他满怀希望地从一所普通大学毕业，带着满腔热血进入社会。当时他选择了这家公司，因为它承诺有很大的发展空间和薪资待遇。起初，情况似乎还不错，他得到了几次小的升职机会，并在团队中赢得了一些尊重。然而，随着经济形势的变化，公司开始裁员，这让他感到了危机。

一个朋友曾建议他换一份工作，但是为了让家里病重的母亲能有稳定的医疗费来源，他不得不选择继续坚守在这份工作岗位上。灰暗的前景和不断增加的工作压力，让他渐渐变得麻木且疲惫。

拖着疲惫的身躯回到出租屋，张鹤之还没来得及将衣服挂到墙上，房东已经敲响了他的房门。"房租，该缴了！"房东的语气毫不留情，让他感到一丝刺骨的寒意。

"好吧，我尽快。"张鹤之无奈地答应，心中只有更多的失落。打开手机，发现短信提示余额不足，连与朋友联系的机会都被切断了。

他懊恼地扔下手机，躺在那单薄的床垫上，望着天花板，脑海里不停浮现出那该死的策划案，失业后的每个可能情景在他脑中盘旋。一瞬间，他竟产生了一种放弃一切的念头，那种无尽的绝望让他感到万念俱灰。

就在这时，脑中突然传来一个清晰的声音，仿佛从另一个世界传来。"宿主，您已获得破解现实世界规则的能力，请进行尝试。"

张鹤之猛地愣住了，不敢相信自己的耳朵。究竟是他太疲劳产生了幻觉，还是这个冰冷的现实终于向他展露了一丝温情？

"这是在做梦吗？"张鹤之自言自语，尝试捏了一下自己的手背，清晰的疼痛让他意识到这一切是真的。

在他的注视下，放在桌边的旧闹钟突然发出微弱的光芒。随着光芒越来越强，闹钟的指针开始迅速倒转，回到了两分钟前。他刚才喝洒了一地的水杯完好无损地躺在桌上，仿佛一切都未发生过。这个神奇的变化令他大惊失色。

系统的声音再次响起："您可以改变现实的属性，赋予它新的功能。但请注意，使用能力需消耗精神力，过度使用可能对身体造成伤害。"

张鹤之的目光变得坚定起来，他下意识地握紧了拳头。内心的狂喜渐渐被冷静和计划取代。这真正的力量让他感到无比振奋，但他同时也意识到，想要彻底改变命运，还需要谨慎行事和不断试验。

为了熟悉和掌握这份能力，张鹤之决定从一些简单的事情开始。他将卧室的灯泡取下来，然后集中精神试图改变其亮度属性。结果灯泡突然闪烁了一下，光线变得比之前更加明亮。这次试验的成功让他信心倍增，但随后出现的头晕目眩也提醒着他这个能力的代价。

“需要找到一个平衡点，”张鹤之默默对自己说。他还记得大学时期他非常理想主义的自己，每天读书到深夜，做着各种天马行空的计划。而今，他终于有机会实现那些梦想了，但是他必须保持警觉。

随着时间的推移，张鹤之逐渐掌握了这个系统的能力和限制。他开始尝试一些小范围的空间操控，比如暂时改变办公桌的大小，以便更有效率地工作。这在早期并未引起任何人的注意，但他显然感觉到自己的工作效率有了显著提升。

“张鹤之，你这个月的业绩居然提升了这么多？”同事李铭在月底的总结会上对他说。张鹤之混掺了个笑，心里却更加坚定了要善用系统的决心。

然而，每次试验成功带来的振奋，也伴随着偶尔的失败挫折。例如，一次他试图让纸片老婆变成真实人物，却因为过度消耗精神力而晕倒，还好并未留下后遗症。这使他更加警觉，明白必须稳扎稳打，切勿急于求成。

与此同时，公司内部的项目招标会将至，这次招标会是公司未来几年的重磅项目，决定了很多同事的前途与命运。在筹备会上，张鹤之捕捉到了一个重要的信息：一个友善的老同事告诉他，有一个尚未公布的内部消息，这次招标会的具体内容可能与他手上的一个未完成的策划案有很大联系。

“也许，这就是我的机会。”张鹤之心中萌生出新的希望。通过系统赋予的力量，他不仅要保护自己，更要抓住这一难得的机遇，去改变现有的命运轨迹。

张鹤之深深吸了一口气，准备好了迎接未知的挑战。

**Comment by wandanan** [comment]
这一张剧情，是我在意见中给出了具体的情节发展，让它填充的，例如：

重构第一章，故事围绕主角的境遇开始，被公司领导欺负，回到家又遭遇房东催缴，手机欠费，此刻他甚至想放弃，然后脑海中响起系统声，他一开始完全不知所措，系统告诉他能带给他破解现实的能力，主角此刻不敢相信如此强大的能力，于是系统给它展示了一下，破解现实的能力第一次展现给读者，第一个破解现实的事件，一定要精彩，神奇，让读者能够感到非常好奇，意识到这一些真实发生后，主角内心狂喜

是否意味着每章都需要做到这个地步

**Comment by MaoXiaoYuZ** [comment]
事实上，我在生成章节剧情时甚至会具体到：
主角被上司张强斥责做不好策划。
主角心中一阵苦涩，回想之前的种种。
……
也就是说剧情会细节到类似分镜稿的地步，这样才能保证后续从剧情中生成的中正文能符合你期望的样子。
所以，在这种设计下，不存在各章剧情连续性的问题。
这样的缺点在于太耗费人力了，不过为了能真正实现让LLM写出能签约的网文，我认为这才是可行之举。

**Comment by wandanan** [comment]
明白了，那也还是需要给定具体的细纲，让ai进行扩写，你设计的RAG抽取到的上下文，会参与每次的扩写是吗

**Comment by MaoXiaoYuZ** [comment]
是的，扩写前会先抽取上下文。
