### ISSUE TITLE
M1 MAC运行报错

### ISSUE THREAD

**Issue by rcy1314** [MaoXiaoYuZ/Long-Novel-GPT#3]
你好，运行环境为M1 MAC，好像不支持pywin32模块及运行demo时报引用Grapefruit库时遇到了错误，有解决方案吗？万分感激

**Comment by MaoXiaoYuZ** [comment]
你说的是AutoChatScript吧，目前只支持Windows平台，后续会更新其他平台。

**Comment by rcy1314** [comment]
> 你说的是AutoChatScript吧，目前只支持Windows平台，后续会更新其他平台。
好吧，期待后续的更新
