### ISSUE TITLE
文心一言调用报错

### ISSUE THREAD

**Issue by zyhxq** [MaoXiaoYuZ/Long-Novel-GPT#30]
User:回答这是一个测试。
(ERROR)ERNIE-Bot:AK(ALTAKN***) is not correct, please check! AK(`ALTAKN***`) 错误, 请检查！ AK/SK should be obtained from https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application
(ERROR)ERNIE-Bot-4:AK(ALTAKN***) is not correct, please check! AK(`ALTAKN***`) 错误, 请检查！ AK/SK should be obtained from https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application

内部有新旧2种授权方式
iam认证，不行
![image](https://github.com/user-attachments/assets/a439ea46-94d4-44db-97a9-c4bd842fa2c3)

旧的方式也不行
![image](https://github.com/user-attachments/assets/55765c0c-4448-401a-9c9e-d8b8d29f1ad6)

请问怎么解决？

**Comment by sorahkasugano** [comment]
/llm_api/baidu_api.py:34，model需要替换下，替换成你创建的服务支持的model
`def stream_chat_with_wenxin(messages, model='ERNIE-Bot', response_json=False):`
`def stream_chat_with_wenxin(messages, model='ERNIE-4.0-8K', response_json=False):`
![image](https://github.com/user-attachments/assets/ac288d79-862d-40c7-9326-c27f10a03232)

**Comment by zyhxq** [comment]
> /llm_api/baidu_api.py:34，model需要替换下，替换成你创建的服务支持的model `def stream_chat_with_wenxin(messages, model='ERNIE-Bot', response_json=False):` `def stream_chat_with_wenxin(messages, model='ERNIE-4.0-8K', response_json=False):` ![image](https://private-user-images.githubusercontent.com/129474927/363639945-ac288d79-862d-40c7-9326-c27f10a03232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjMzMzAsIm5iZiI6MTcyNTYyMzAzMCwicGF0aCI6Ii8xMjk0NzQ5MjcvMzYzNjM5OTQ1LWFjMjg4ZDc5LTg2MmQtNDBjNy05MzI2LWMyN2YxMGEwMzIzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxMTQzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzllMDk5NjUyYmUxZmJlMmU5MDU0YzVjOTZiOGU0Y2E3MTk5YjRjMmQyZmZmOGU2M2IxZTUwYThmMjZlOTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZNbW_0yfIuaINvna6IikwWc3BCBJtYH_18HEpPsQ8cg)

Thank you very much!
非常感谢！

**Comment by MaoXiaoYuZ** [comment]
新版本已发布，GPT模块后续支持，先可以尝试在线demo。
