### ISSUE TITLE
文心一言的那个小说大模型可以安排上吗？

### ISSUE THREAD

**Issue by huang-heavenly-Emperor** [MaoXiaoYuZ/Long-Novel-GPT#31]
![Snipaste_2024-09-06_09-07-56](https://github.com/user-attachments/assets/a1dd6b75-f158-4f69-9fd7-16dc73f9d717)

**Comment by MaoXiaoYuZ** [comment]
可以的，已经在日程中了。

**Comment by huang-heavenly-Emperor** [comment]
> 可以的，已经在日程中了。

这个api有点小贵，玩不起，哭了

**Comment by MaoXiaoYuZ** [comment]
在线Demo可以选择文心小说大模型了，欢迎尝试
