### ISSUE TITLE
文心一言api

### ISSUE THREAD

**Issue by xiaozheming** [MaoXiaoYuZ/Long-Novel-GPT#32]
![image](https://github.com/user-attachments/assets/a5bd9f4e-7a03-4d8f-8446-ef26a9a42383)
使用了ak，sk
但是还是报错。并且model也调整为了ERNIE-4.0-8K
User:回答这是一个测试。
(ERROR)ERNIE-Bot:no enough credential found, use any one of (access_key, secret_key), (ak, sk), (access_token) in api v1 or any of (ak, sk), (bearer token) in api v2
(ERROR)ERNIE-Bot-4:no enough credential found, use any one of (access_key, secret_key), (ak, sk), (access_token) in api v1 or any of (ak, sk), (bearer token) in api v2

有没有大佬可以帮我瞅一眼

**Comment by MaoXiaoYuZ** [comment]
https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application/v1
你访问这个链接看看

**Comment by xiaozheming** [comment]
大佬，确实就是这个地址。
图1是我创建的应用，图二是安全认证的ak，sk。图三是我使用了ak，sk后的报错
<img width="1501" alt="image" src="https://github.com/user-attachments/assets/0ee478cc-ef8b-4b60-95d5-0fc0c7dd7b2f">
<img width="2316" alt="image" src="https://github.com/user-attachments/assets/814c2e16-c2d8-4cd6-b275-54b915b27c83">
<img width="1618" alt="image" src="https://github.com/user-attachments/assets/17069efa-e8f7-4478-b7ea-5c3f64672493">

**Comment by MaoXiaoYuZ** [comment]
可以在千帆提供的demo中测试下：
https://console.bce.baidu.com/support/#/api?product=QIANFAN&project=%E5%8D%83%E5%B8%86ModelBuilder&parent=ERNIE%204.0&api=rpc%2F2.0%2Fai_custom%2Fv1%2Fwenxinworkshop%2Fchat%2Fcompletions_pro&method=post

**Comment by xiaozheming** [comment]
很奇怪的就是，我的ak，sk在千帆的测试中是ok的，但是在项目中却报错。
大佬我想请问下，我用的分支是1.5，会和这个有关系吗

**Comment by huang-heavenly-Emperor** [comment]
> 可以在千帆提供的demo中测试下： https://console.bce.baidu.com/support/#/api?product=QIANFAN&project=%E5%8D%83%E5%B8%86ModelBuilder&parent=ERNIE%204.0&api=rpc%2F2.0%2Fai_custom%2Fv1%2Fwenxinworkshop%2Fchat%2Fcompletions_pro&method=post

大佬下个版本什么时候完成啊

**Comment by MaoXiaoYuZ** [comment]
> 很奇怪的就是，我的ak，sk在千帆的测试中是ok的，但是在项目中却报错。 大佬我想请问下，我用的分支是1.5，会和这个有关系吗

已经确认了是因为qinfan这个包的版本更新导致的，可以考虑回退到一个之前的版本，具体可以运行下面这条命令：
```
pip install qianfan==0.3.17
```

**Comment by MaoXiaoYuZ** [comment]
新版本已发布，可以尝试在线demo。

**Comment by huang-heavenly-Emperor** [comment]
> 新版本已发布，可以尝试在线demo。

这就试试

**Comment by xiaozheming** [comment]
<img width="342" alt="image" src="https://github.com/user-attachments/assets/51143729-efe2-4cb5-a99d-f843ec8c0ac4">
已经使用了0.3.17，但似乎还是没有解决问题

**Comment by MaoXiaoYuZ** [comment]
你打开在线Demo，然后输入你的api-key，点击测试来试试，看看是否有效。
在线Demo的api-key只会保存在本地，可以放心使用。
