### ISSUE TITLE
openai api_key

### ISSUE THREAD

**Issue by richfox** [MaoXiaoYuZ/Long-Novel-GPT#33]
openai api_key 这个测试通不过，显示
User:Say this is a test
(ERROR)gpt-4-1106-preview:Connection error.
(ERROR)gpt-3.5-turbo-1106:Connection error.

**Comment by MaoXiaoYuZ** [comment]
新版本已发布，GPT模块后续支持，先可以尝试在线demo。

**Comment by MaoXiaoYuZ** [comment]
新版本已经推送，支持适配OpenAI接口格式的自定义模型。
