### ISSUE TITLE
error：信息: 用提供的模式无法找到文件。

### ISSUE THREAD

**Issue by zirenlegend** [MaoXiaoYuZ/Long-Novel-GPT#35]
提示，信息: 用提供的模式无法找到文件。
无法访问页面

**Comment by zirenlegend** [comment]
![屏幕截图 2024-11-02 160259](https://github.com/user-attachments/assets/9044cdc3-6037-46ee-8120-f335d786eaf9)

**Comment by zirenlegend** [comment]
![屏幕截图 2024-11-02 160408](https://github.com/user-attachments/assets/65a871ac-3062-4613-b848-dce1234702ad)

**Comment by MaoXiaoYuZ** [comment]
访问本机的:
http://127.0.0.1:7860/

**Comment by zirenlegend** [comment]
> 访问本机的: http://127.0.0.1:7860/

哈哈哈哈哈哈哈哈哈，感谢感谢，都被自己给逗笑了
