### ISSUE TITLE
【功能建议】支持OpenAI格式，以及自定义接口地址、自定义模型名称

### ISSUE THREAD

**Issue by Ruler27** [MaoXiaoYuZ/Long-Novel-GPT#37]
有一些免费的API中转项目，可以比较方便的管理各种公司的模型，国内外的模型大多都支持，转接出来一般是OpenAI格式

所以建议作者可以支持OpenAI格式，以及自定义接口地址、自定义模型名称（最好是能直接在WebUI上设置）

这样作者这边就没必要在初期花费较多精力在接口适配上，可以先完善功能，之后再考虑原生支持其他格式

**Comment by MaoXiaoYuZ** [comment]
嗯，很好的建议，我正在着手实现相关功能，将支持GPT模型以及兼容Openai接口的模型，该更新预计在一周内就会上线，敬请关注。

**Comment by MaoXiaoYuZ** [comment]
新版本已经推送，支持适配OpenAI接口格式的自定义模型。
