### ISSUE TITLE
OpenAI API Key 测试失败：Connection error.

### ISSUE THREAD

**Issue by iamcheyan** [MaoXiaoYuZ/Long-Novel-GPT#38]
![image](https://github.com/user-attachments/assets/f0de0dda-ee53-4d6b-9000-8a21b494e7e6)

**Comment by MaoXiaoYuZ** [comment]
如果没有api base url或代理，国内是访问不了OpenAI API的。

**Comment by iamcheyan** [comment]
明白了，我在日本
API Base URL是需要填入：https://api.openai.com/v1

**Comment by MaoXiaoYuZ** [comment]
嗯，看起来是个bug，之后我会修复的。
