### ISSUE TITLE
这步骤如何操作：在AutoChatScript的demo <设置> 页面中，填写ChatGPT的base_url为：

### ISSUE THREAD

**Issue by cloveric** [MaoXiaoYuZ/Long-Novel-GPT#4]
在AutoChatScript的demo <设置> 页面中，填写ChatGPT的base_url为：http://localhost:8000/v1/

没有看到demo的设置页面

AutoChatScript已经安装好。

以及在运行
cd Long-Novel-GPT
python demo/app.py

时，提示To create a public link, set `share=True` in `launch()`.

**Comment by MaoXiaoYuZ** [comment]
提示不用管，直接打开链接即可，然后你就可以在浏览器看到demo了。
