### ISSUE TITLE
Error 操作过程中发生错误：请求的文本过长，超过最大tokens:4096。

### ISSUE THREAD

**Issue by zirenlegend** [MaoXiaoYuZ/Long-Novel-GPT#42]
我是用的是doubao-pro-32k和doubao-lite-32k，4096应该没有超过限制，以及我看提纲限定在了20个字（希望放开限制），扩展全部**旁边中的输入框是干嘛用的呢，我输入后感觉没有任何效果

**Comment by MaoXiaoYuZ** [comment]
20字的限制是因为V1.8版本是从一个创意生成全书，而创意往往就是人的一个想法，灵光一闪。

当然，还有就是不希望用户将过多的精力放在一个初始的量的优化上，而且在整个过程中利用扩写不断地去优化。（后续会放开，目前20字确实过少）

扩展全部**旁边中的输入框是为了后续自己输入意见，让AI根据你输入的意见进行全书的重写。（本质上目前扩写其实就是我代替你输入了扩写意见）但在V1.8版本这个功能没有测试，你可以试试看看输入后，Prompt预览中是否会出现你输入的意见，如果有，说明有用。

**Comment by MaoXiaoYuZ** [comment]
V1.9版本发布了，在线Demo输入的限制由20提高到200，并支持多行。
