### ISSUE TITLE
GPT4也有点差强人意

### ISSUE THREAD

**Issue by kankanai** [MaoXiaoYuZ/Long-Novel-GPT#6]
反馈一个问题：
新建了一个章节后，存在了第一章，再新建章节，选择了分卷，还是第一章，生成到章节剧情也是第一章。
![image](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/142068366/9ba545b9-35fb-491d-9eab-bc5c1b012998)

夜色已经深沉，寒风中还残留着白日的嘈杂却又多了几分不为人知的寂静。李晨依稀记得自己正踏足于深山之中寻找古迹，脚下踏打的破败石板忽然一阵剧烈的光芒闪烁，紧接着便是天旋地转。当他再次睁开眼时，世界已经变了模样。

石板道变成了黄土路，穿着奇特衣裳的人们来往匆忙。他穿着的运动装如同异类，在这个时代格格不入，被好奇的眼光追逐。

他感到困惑，混乱，不敢相信这是现实。手中沉甸甸的玉佩犹如发烫的铁块，刺痛着他的掌心，似乎在告诉他一切不是梦。

在宫廷外徘徊，李晨尝试着理解眼前的一切。宫廷内的建筑比任何一本史籍描述的都要宏伟，金色的屋顶在日光下闪耀着璀璨的光芒，落寞的鸦雀在宫墙外盘旋。

这里的生活节奏与他熟悉的现代社会完全不同。处处可见行走于宫廷中的太监和宫女，他们或忙碌、或聊天，每一个动作都充满了规矩和秩序。

在一次迷茫的徘徊中，李晨结识了一个名叫小李的太监，他透露出不同于其他人的友好和狡黠。小李看似平凡，却对这里的人人物和地理颇为了解，他变成了李晨了解这个世界的眼睛。

不久，李晨又遇到了小红，一位在皇宫中任职的女医生，她具有治愈之手及广博的知识。在一次无心揭开玉佩的秘密中，李晨透露了他来自另一个世界的信息，小红虽然震惊却也表现出浓厚的兴趣。两人的友情逐渐加深，在险恶的宫廷中，他们成了李晨最稳固的依靠。

李晨渐渐适应了这个世界的节奏，开始尝试找到那神秘玉佩的使用之法。每当闲暇之时，他都会默默地研究，尝试摸索着那层层叠叠的神秘纹路，寻找着它发出光芒的秘密。可每次当光芒初现，他的心脏都会剧烈地跳动，恍如有种力量即将将他带离这时空，然后，在那一刻却总是不了了之。

日复一日，李晨的步伐越发坚定，他知道，在这个陌生而又危机四伏的时代，他只有变得更强，才能找到回家的路。与小李、小红共度的每一个日日夜夜，都让他对他们产生了深厚的感情，也让他更加渴望掌握玉佩的奥秘，寻找属于他的未来。

**Comment by kankanai** [comment]
重新修改了一下提示词，强了一点

凤鸣九天，龙吟云海。朝阳初破，晨曦照耀金碧辉煌的红墙黄瓦。在这气吞山河的皇宫之中，李晨站在宏伟的慈宁宫之前，穿越而来的他如同一只迷失了方向的孤鹰，谨慎而孤独。光怪陆离的宫廷生活让他心旷神怡的同时，也感到了前所未有的渺小与不安。

李晨手中紧紧把握着那块见证了他命运跌宕的玉佩，它散发着微弱而神秘的光芒，仿佛拥有古老的灵魂在其中低语。玉佩的莹润与温润，与他掌心的温热交融，似乎在无声诉说时间的秘密。然而，他如何才能解开这个时空的迷团，还能否找到回归现代文明的路途？

在皇宫的角落里，小李和小红，这两位于宫斗算计之余依旧保持一丝朴实与温暖的人们，成了他在这个时代最为真诚的朋友。小李那一双“能说会道”的眼睛里隐藏着对这乾坤一笑的豁达，而小红巧手仁心，使得她的医术仿佛掌握着鬼神的点金之术。

"李晨啊，你的古怪举止，确实令人琢磨不透，"小李戏谑着，试图从李晨口中掏出这时空旅者的秘密。
"我只是…怀念故土罢了。"李晨的话语充满了无尽的远思与牵挂。

三人围坐在屋檐下，小李与小红固然是广交朋友的能手，但彼此之间的对话总能触及灵魂的深处，小李慧黠而目光深邃，小红的语气总透着几分坚定和关怀，每个字每句话仿佛都是连心符，悄无声息地温暖着彼此。

"武林秘籍"一词忽地闯入他们的谈话，使得李晨的心微微一颤。在这个久远的时代，他若能掌握那些高深的武艺，的确是自保之良策。他想象着那些行云流水的剑法和威猛霸气的拳招，恰似一位初试啼声的雏鹰，对于翱翔蓝天抱有着无尽的渴望。

但他在心中又何尝不清楚，每一次挥拳抬腿的背后，都是无边的困顿和挑战。他必须学会在这个光怪陆离的时代中生存、适应，甚至崭露头角。时间如沙漏般流逝，他知道，他要把握住每一粒逝去的沙粒。

皇宫的上空，秋高气爽，一队队飞鸟呼啸而过，伴随着远方的鼓声阵阵，拨动着心弦。李晨闭上眼，聆听着古代的风声，呼吸着曾经他只能在史书上触摸到的空气。他开始了解，只有融入才能找到归途，只有坚韧才能不迷失方向。

他将守候在这个辉煌与黑暗并存的世界，他将在这旷古烁今的岁月里找寻属于自己的明天。而现在，李晨和他的新朋友们，他们的故事正在这千古风华的背景下，缓缓揭开序幕……

**Comment by MaoXiaoYuZ** [comment]
目前一次生成结果几乎不能直接用（指达到签约水准），需要不断润色。

之后会上线自定义prompt以及更好的润色功能。

**Comment by MaoXiaoYuZ** [comment]
新建章节目前的意思等同“新建所有章节”，而不是“开始新的一章”

**Comment by xiewenqian** [comment]
gpt会迫不及待滴让故事剧情结束
