### ISSUE TITLE
在使用ChatGPT作为API的部分不知道怎么操作

### ISSUE THREAD

**Issue by DannyWu25** [MaoXiaoYuZ/Long-Novel-GPT#9]
您好，我按照教程操作下来，在使用ChatGPT作为API的部分，运行python openai_api.py --server-port 8000之后只显示This Say a is Test!，不知道后续该怎么操作，能否完善一下教程呢
![微信截图_20240311161125](https://github.com/MaoXiaoYuZ/Long-Novel-GPT/assets/96119579/222ace66-0631-4c62-8041-a0e35d0e6a50)

**Comment by MaoXiaoYuZ** [comment]
我估计是脚本把openai_api文件内容给改了，你看下openai_api文件是不只剩一行了

**Comment by MaoXiaoYuZ** [comment]
重新下载这个文件即可

**Comment by tianxiazaiwo** [comment]
> > 我估计是脚本把openai_api文件内容给改了，你看下openai_api文件是不剩一行了
> 
> 是的，请问是需要重新安装吗

您好，大哥，请问您安装成功了吗，可以加个微信交流下。我微信号tianxiazaiwowo，如果加，备注里面写下 github

**Comment by DannyWu25** [comment]
> > > 我估计是脚本把openai_api文件内容给改了，你看下openai_api文件是不剩一行了
> > 
> > 
> > 是的，请问是需要重新安装吗
> 
> 您好，大哥，请问您安装成功了吗，可以加个微信交流下。我微信号tianxiazaiwowo，如果加，备注里面写下 github

安装成功了，按作者的说做就行了

**Comment by DannyWu25** [comment]
> > > > > 我估计是脚本把openai_api文件内容给改了，你看下openai_api文件是不剩一行了
> > > > 
> > > > 
> > > > 是的，请问是需要重新安装吗
> > > 
> > > 
> > > 您好，大哥，请问您安装成功了吗，可以加个微信交流下。我微信号tianxiazaiwowo，如果加，备注里面写下 github
> > 
> > 
> > 安装成功了，按作者的说做就行了
> 
> 您也是用openai api私钥吗，申请私钥后，在openai中需要绑定自己的信用卡，程序才能正常运行对吧，以后运行都需要扣openai费用吗？。您方便的话，可以看下帮我看下，这是我提的问题：#11 可以翻到问题最底下，非常感谢

用openAI的API的话免费额度用完之后要付费的，用chatGPT网页版的话又很麻烦，而且我试下来效果也不好
